import type { AIProvider, AnnotationRequest, AnnotationResult, SemanticMatchRequest, SemanticMatchResult } from '../types.js'
import { WHYTHO_VERSION } from '../../core/constants.js'

export const nullProvider: AIProvider = {
  name: 'null',

  async generateAnnotation(request: AnnotationRequest): Promise<AnnotationResult> {
    const now = new Date().toISOString()
    const type = request.type

    const baseFrontmatter = {
      whytho: WHYTHO_VERSION,
      type,
      created: now,
      updated: now,
    }

    return {
      frontmatter: baseFrontmatter,
      body: `<!-- Generated by null provider — replace with real annotations -->\n\n## Purpose\n\n[No AI provider configured.]\n`,
    }
  },

  async matchSemanticFingerprint(_request: SemanticMatchRequest): Promise<SemanticMatchResult> {
    return { matchedIndex: null, confidence: 0 }
  },
}
