import type { AIProvider, AnnotationRequest, AnnotationResult, SemanticMatchRequest, SemanticMatchResult, AssessPushNotesRequest, AssessPushNotesResult } from '../types.js'
import { WHYTHO_VERSION } from '../../core/constants.js'

export const nullProvider: AIProvider = {
  name: 'null',

  // eslint-disable-next-line @typescript-eslint/require-await
  async generateAnnotation(request: AnnotationRequest): Promise<AnnotationResult> {
    const now = new Date().toISOString()
    const type = request.type

    const baseFrontmatter = {
      whytho: WHYTHO_VERSION,
      type,
      created: now,
      updated: now,
    }

    return {
      frontmatter: baseFrontmatter,
      body: `<!-- Generated by null provider — replace with real annotations -->\n\n## Purpose\n\n[No AI provider configured.]\n`,
    }
  },

  // eslint-disable-next-line @typescript-eslint/require-await
  async matchSemanticFingerprint(_request: SemanticMatchRequest): Promise<SemanticMatchResult> {
    return { matchedIndex: null, confidence: 0 }
  },

  // eslint-disable-next-line @typescript-eslint/require-await
  async assessPushNotes(request: AssessPushNotesRequest): Promise<AssessPushNotesResult> {
    // Null provider keeps all notes as complementary (safe default)
    return {
      assessments: request.pushNotes.map((n) => ({ index: n.index, verdict: 'complementary' as const })),
    }
  },
}
